# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-22 19:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('beltreviewer', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='name',
            new_name='author',
        ),
        migrations.RenameField(
            model_name='book',
            old_name='name',
            new_name='title',
        ),
        migrations.RemoveField(
            model_name='book',
            name='author',
        ),
        migrations.AddField(
            model_name='book',
            name='writer',
            field=models.ForeignKey(default='0', on_delete=django.db.models.deletion.CASCADE, related_name='writer', to='beltreviewer.Author'),
        ),
    ]
